1.2.0 (feat): + Fixed bug and improved code
* Improved UI.
* Added a verifier to check if all commands were installed.
* Enhanced code consistency.
* Removed ripgrep.

diff --git a/impzy b/impzy
--- a/impzy
+++ b/impzy
@@ -11,13 +11,34 @@ bold="\e[1m"
 end="\e[0m"
 
 ### Variables globales
-IN_OPT=${1:-.}
-IN_PATH=${2:-.}
+OPTION_INPUT=${1:-.}
+PATH_INPUT=${2:-.}
 INDEX_FILE="index.jsx"
-VARS_NAME=()
+ELEM_NAME=()
+COUNTER=0
+
+### Función para verificar si un comando está instalado
+function check_command() {
+  if ! command -v "$1" &> /dev/null; then
+    echo -e " \"$1\" is not installed. Install it to continue. \n"
+    return 1
+  else
+    return 0
+  fi
+}
+
+### Verificar si fd y ripgrep estan instalados
+check_command "fd"
+fd_installed=$?
+
+if [ $fd_installed -eq 0 ]; then
+  echo -e " ${bold}Initializing...${end}"
+else
+  exit
+fi
 
 ### Mostrar ayuda
-function func_show_help() {
+function show_help() {
   cat << EOF
 
   Usage:
@@ -35,90 +56,95 @@ EOF
 }
 
 ### Crear o limpiar el archivo "index.jsx"
-func_initialize_index_file() {
+function initialize_index_file() {
   > "$INDEX_FILE"
 }
 
 ### Procesar los archivos JSX y generar las importaciones
-func_process_jsx_files() {
-  local counter=0
+function process_jsx_files() {
   # Buscar todos los archivos .jsx en el directorio actual y sus subdirectorios
-  local find
-  find=$(fd --full-path "$IN_PATH" -e "jsx")
+  local find_files=$(fd --full-path "$PATH_INPUT" -e "jsx")
 
-  for file in $find; do
-    # Formatear la ruta del archivo
-    local file_path
-    file_path=$(echo "$file" | sed 's/^\.\///;s/\.jsx$//')
-    # Extraer el nombre del archivo sin la extensión
-    local file_name
-    file_name=$(basename "$file" .jsx)
-    # Ignorar archivos con el nombre 'index.jsx'
-    if [ "$file_name" == "index" ]; then
-      continue
+  for file in $find_files; do
+    if [ -s "$file" ]; then
+      # Formatear la ruta del archivo
+      local unpathed_file=$(echo "$file" | sed 's/^\.\///;s/\.jsx$//')
+
+      # Extraer el nombre del archivo sin la extensión
+      local file_name=$(basename "$file" .jsx)
+
+      # Ignorar los archivoz vacios o con el nombre "index"
+      local matches=$(grep -oP "export\s+const\s+\K\w+" "$file")
+      if [[ "$file_name" == "index" || -z "$matches" || -z "${matches// }" ]]; then
+        continue
+      fi
+
+      local match_found+=("$matches")
+      local array_matches=(${matches})
+      echo -e " ${gray}* $file${end}"
+
+      # Añadir los datos a "index.jsx"
+      if [ ${#array_matches[@]} -gt 1 ]; then
+        local add_to_index=()
+
+        for elem in "${array_matches[@]}"; do
+          add_to_index+=("$elem,")
+          ((COUNTER+=1))
+        done
+
+        ELEM_NAME+=("${add_to_index[*]}")
+        echo "import { ${add_to_index[*]} } from './${unpathed_file}.jsx';" >> "$INDEX_FILE"
+      else
+        ELEM_NAME+=("${match_found[*]},")
+        echo "import { ${match_found[*]} } from './${unpathed_file}.jsx';" >> "$INDEX_FILE"
+        ((COUNTER+=1))
+      fi
+      match_found=()
     fi
-    # Almacenar los datos en una variable
-    local find_export_vars
-    find_export_vars=($(rg --color=never 'export\s+const\s+\w+' "$file" | awk '{print $3}' | sed 's/;//g' | sed 's/,//g' | sed 's/}/\n/g'))
-    # Ignorar los datos vacios
-    if [ "${find_export_vars[*]}" == "" ]; then
-      continue
-    fi
-    # Añadir los datos a "index.jsx"
-    if [ ${#find_export_vars[@]} -gt 1 ]; then
-      local add_to_index=()
-      for elem in "${find_export_vars[@]}"; do
-        add_to_index+=("$elem,")
-        ((counter+=1))
-      done
-      add_to_index[-1]=${find_export_vars[-1]}
-      echo "import { ${add_to_index[*]} } from './${file_path}.jsx';" >> "$INDEX_FILE"
-      VARS_NAME+=("${add_to_index[*]},")
-    else
-      echo "import { ${find_export_vars[*]} } from './${file_path}.jsx';" >> "$INDEX_FILE"
-      VARS_NAME+=("${find_export_vars[*]},")
-      ((counter+=1))
-    fi
-    find_export_vars=()
   done
-  echo -e " ${bold}Number of imported components ${end}:"
-  echo -e " ${gray}${counter}${end}"
+
+  echo -e " ${bold}Number of imported elements:${end} ${gray}${COUNTER}${end}\n"
 }
 
 ### Agregar la exportación al final del archivo de "index.jsx"
-func_finalize_index_file() {
+function finalize_index_file() {
   echo " " >> "$INDEX_FILE"
   echo "export {" >> "$INDEX_FILE"
-
-  for elem in "${VARS_NAME[@]}"; do
-    echo " $elem" >> "$INDEX_FILE"
+  for elem in "${ELEM_NAME[@]}"; do
+    echo "  $elem" >> "$INDEX_FILE"
   done
   echo "}" >> "$INDEX_FILE"
 }
 
 ### Ejecutar el script
-func_main() {
-  if ! [ -d "$IN_PATH" ]; then
-    echo " Invalid directory."
+function main() {
+  if ! [ -d "$PATH_INPUT" ]; then
+    echo -e " Invalid directory. \n"
   else
-    func_initialize_index_file
-    func_process_jsx_files
-    func_finalize_index_file
+    initialize_index_file
+    process_jsx_files
+    if [ ${COUNTER} -gt 0 ]; then
+      finalize_index_file
+      exit
+    fi
+    if [ $(wc -c < $INDEX_FILE) -eq 0 ]; then
+      rm -rf $INDEX_FILE
+    fi
   fi
 }
 
 ### Opciones
-case "${IN_OPT}" in
+case "${OPTION_INPUT}" in
   --help|-h)
-    func_show_help
+    show_help
     ;;
   --version|-v)
     echo "v1.1.3"
     ;;
   --parse|-p)
-    func_main
+    main
     ;;
   *)
-    echo " Invalid option."
+    echo -e " Invalid option. \n"
     ;;
 esac
